In [1]:
import matplotlib.pyplot as plt
import matplotlib as matplt
import numpy as np
import pandas as pd
import seaborn as sns
import os
import glob
import math
import statistics
import tables

np.set_printoptions(precision=3, suppress=True)

from matplotlib.gridspec import GridSpec

In [2]:
print (np.__version__)
print (pd.__version__)
print (sns.__version__)
print (matplt.__version__)
print (tables.__version__)

1.22.3
1.4.1
0.11.2
3.5.1
3.7.0

## Profile GEEMM tasks only

```

[****] TIME(s)      7.06727 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :    2263.957503 gflops - ENQ&PROG&DEST      7.49736 :    2134.085688 gflops - ENQ      0.27030 - DEST      0.15979
[****] TIME(s)      3.50326 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :    4567.170588 gflops - ENQ&PROG&DEST      5.21118 :    3070.322892 gflops - ENQ      1.56624 - DEST      0.14167
[****] TIME(s)      3.99480 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :    4005.209511 gflops - ENQ&PROG&DEST      5.37585 :    2976.272018 gflops - ENQ      1.24757 - DEST      0.13348
[****] TIME(s)      0.77603 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   20617.670354 gflops - ENQ&PROG&DEST      2.16060 :    7405.367489 gflops - ENQ      1.25310 - DEST      0.13146
[****] TIME(s)      0.79466 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   20134.520392 gflops - ENQ&PROG&DEST      1.74424 :    9173.025767 gflops - ENQ      0.81746 - DEST      0.13213
[****] TIME(s)      0.82880 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   19304.971485 gflops - ENQ&PROG&DEST      1.51983 :   10527.487430 gflops - ENQ      0.55892 - DEST      0.13211
[****] TIME(s)      1.40553 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   11383.630668 gflops - ENQ&PROG&DEST      2.30994 :    6926.589629 gflops - ENQ      0.77341 - DEST      0.13100
[****] TIME(s)      0.78216 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   20456.241068 gflops - ENQ&PROG&DEST      1.42638 :   11217.192435 gflops - ENQ      0.51447 - DEST      0.12976
[****] TIME(s)      0.93868 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   17045.157896 gflops - ENQ&PROG&DEST      1.54313 :   10368.536904 gflops - ENQ      0.47201 - DEST      0.13243
[****] TIME(s)      0.97549 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   16402.052070 gflops - ENQ&PROG&DEST      1.49600 :   10695.154573 gflops - ENQ      0.39577 - DEST      0.12475
[****] TIME(s)      1.79954 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :    8891.176050 gflops - ENQ&PROG&DEST      2.20845 :    7244.894975 gflops - ENQ      0.27747 - DEST      0.13144
[****] TIME(s)      1.30024 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   12305.456605 gflops - ENQ&PROG&DEST      2.15351 :    7429.723010 gflops - ENQ      0.72829 - DEST      0.12498
[****] TIME(s)      3.30158 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :    4846.163159 gflops - ENQ&PROG&DEST      4.34980 :    3678.325989 gflops - ENQ      0.90480 - DEST      0.14342
[****] TIME(s)      1.54532 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   10353.838489 gflops - ENQ&PROG&DEST      2.48971 :    6426.459985 gflops - ENQ      0.81412 - DEST      0.13026
[****] TIME(s)      0.96522 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   16576.485269 gflops - ENQ&PROG&DEST      1.97018 :    8121.096735 gflops - ENQ      0.87949 - DEST      0.12547
[****] TIME(s)      1.93919 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :    8250.884586 gflops - ENQ&PROG&DEST      2.94444 :    5433.973201 gflops - ENQ      0.86798 - DEST      0.13727
[****] TIME(s)      0.99949 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   16008.084627 gflops - ENQ&PROG&DEST      1.95009 :    8204.750538 gflops - ENQ      0.82471 - DEST      0.12589
[****] TIME(s)      0.82409 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   19415.471576 gflops - ENQ&PROG&DEST      1.24812 :   12819.329642 gflops - ENQ      0.28978 - DEST      0.13425
[****] TIME(s)      1.00124 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   15980.228127 gflops - ENQ&PROG&DEST      1.66924 :    9585.195931 gflops - ENQ      0.54332 - DEST      0.12468
[****] TIME(s)      1.03462 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   15464.653143 gflops - ENQ&PROG&DEST      1.50813 :   10609.183712 gflops - ENQ      0.34820 - DEST      0.12531

```

## Import traces

In [144]:
node_0_hd5 = pd.HDFStore("./traces/GEMM_Nomig-0.prof.h5")
node_0_events = node_0_hd5.events
#node_0_events.tail()

In [145]:
node_1_hd5 = pd.HDFStore("./traces/GEMM_Nomig-1.prof.h5")
node_1_events = node_1_hd5.events
#node_1_events.tail()

In [146]:
node_2_hd5 = pd.HDFStore("./traces/GEMM_Nomig-2.prof.h5")
node_2_events = node_2_hd5.events
#node_2_events.tail()

In [147]:
node_3_hd5 = pd.HDFStore("./traces/GEMM_Nomig-3.prof.h5")
node_3_events = node_3_hd5.events
node_3_events.tail()

,taskpool_id,type,n,exec_time_end,dc_key,id,priority,dc_dataid,second_queue_time,trc,...,tpid,tid,dst,size,data_key,k,loc_B,loc_A,dc_id,dc_padding
114492,46,3,None,None,None,193,None,None,None,None,...,NaN,NaN,NaN,None,None,None,None,None,None,None
114493,46,13,None,None,None,193,None,None,None,None,...,NaN,NaN,NaN,None,None,None,None,None,None,None
114494,46,19,15,None,140727451387712,305,0,305,None,0,...,NaN,NaN,NaN,None,None,None,None,None,None,None
114495,46,3,None,None,None,305,None,None,None,None,...,NaN,NaN,NaN,None,None,None,None,None,None,None
114496,46,13,None,None,None,305,None,None,None,None,...,NaN,NaN,NaN,None,None,None,None,None,None,None

In [148]:
node_3_events.keys()

Index(['taskpool_id', 'type', 'n', 'exec_time_end', 'dc_key', 'id', 'priority',
       'dc_dataid', 'second_queue_time', 'trc', 'loc_C', 'exec_time_start',
       'first_queue_time', 'stage_out_time_end', 'stream_id',
       'first_stage_in_time_start', 'class_id', 'node_id', 'begin',
       'nb_first_stage_in_h2d', 'sec_stage_in_time_end', 'nb_first_stage_in',
       'ready_tasks', 'nb_sec_stage_in_d2d', 'exec_stream_index',
       'nb_sec_stage_in', 'select_time', 'clock_speed', 'mig_status',
       'nb_sec_stage_in_h2d', 'sec_stage_in_time_start', 'complete_time_end',
       'tcid', 'end', 'sec_waiting_tasks', 'device_index', 'm', 'task_count',
       'first_waiting_tasks', 'task_type', 'complete_time_start', 'flags',
       'stage_out_time_start', 'nb_first_stage_in_d2d', 'complete_time',
       'first_stage_in_time_end', 'src', 'msg_size', 'tpid', 'tid', 'dst',
       'size', 'data_key', 'k', 'loc_B', 'loc_A', 'dc_id', 'dc_padding'],
      dtype='object')

In [149]:
node_3_events['complete_time'].unique()

array([4825649282.0, None, 4860788603.0, ..., 57459165997.0,
       57596292887.0, 57596379497.0], dtype=object)

In [150]:
node_3_events['task_type'].unique()

array([None, 0.0], dtype=object)

In [151]:
def filter_data_frame(df):
   
    df = df.astype(float)
    
    # consider only compute kernels
    #df = df.loc[ df['task_type'] == 0 ] 
    
    # remove first run
    df = df.loc[ df['taskpool_id'] > 8 ] 
    
    df.reset_index(drop=True, inplace=True)
    

    
    return df

In [152]:
node_0_ref = filter_data_frame(node_0_events)
node_0_ref.head()

,select_time,sec_stage_in_time_end,stage_out_time_start,tcid,stage_out_time_end,sec_stage_in_time_start,first_stage_in_time_end,nb_first_stage_in,second_queue_time,device_index,...,tpid,dst,tid,size,dc_id,k,dc_padding,loc_B,loc_A,data_key
0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [153]:
node_1_ref = filter_data_frame(node_1_events)
node_1_ref.head()

,sec_stage_in_time_start,task_type,priority,tid,select_time,exec_time_start,dc_key,mig_status,stage_out_time_start,nb_first_stage_in,...,stream_id,complete_time_start,dst,loc_B,data_key,dc_padding,loc_A,dc_id,size,k
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [154]:
node_2_ref = filter_data_frame(node_2_events)
node_2_ref.head()

,clock_speed,exec_time_start,begin,complete_time_end,select_time,exec_time_end,exec_stream_index,second_queue_time,first_stage_in_time_end,first_queue_time,...,msg_size,tpid,tid,loc_A,dc_id,loc_B,size,data_key,dc_padding,k
0,NaN,NaN,9.238215e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,9.238266e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,9.238296e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,9.238337e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,9.238373e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [155]:
node_3_ref = filter_data_frame(node_3_events)
node_3_ref.head()

,taskpool_id,type,n,exec_time_end,dc_key,id,priority,dc_dataid,second_queue_time,trc,...,tpid,tid,dst,size,data_key,k,loc_B,loc_A,dc_id,dc_padding
0,10.0,3.0,NaN,NaN,NaN,21.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10.0,3.0,NaN,NaN,NaN,741.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10.0,13.0,NaN,NaN,NaN,741.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10.0,3.0,NaN,NaN,NaN,153.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10.0,13.0,NaN,NaN,NaN,153.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [156]:
node_3_ref['class_id'].unique()

array([nan,  5.])

In [ ]:
GEMM_0_ref = filter_data_frame(node_0_events)
node_0_ref.head()

In [157]:


fig = plt.figure(figsize=(20, 20))
gs = GridSpec(nrows=5, ncols=1)

colours=['red','red','orange','orange','orange','orange','orange','blue','blue','red','blue','red','blue', 'blue','red', 'blue', 'orange', 'blue','blue']

gflops = [4567.170588, 4005.209511, 20617.670354, 20134.520392, 19304.971485, 11383.630668, 20456.241068, 17045.157896, 16402.052070, 8891.176050, 12305.456605, 4846.163159, 10353.838489, 16576.485269, 8250.884586, 16008.084627, 19415.471576, 15980.228127, 15464.653143]
runs = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]



ax4 = fig.add_subplot(gs[0, 0])
plt.plot(runs, gflops, marker=11)

plt.axhline(y=8500,  color='red', linestyle='--')
plt.axhline(y=18000,  color='blue', linestyle='--')
plt.axhline(y=24000, color='orange', linestyle='--')

plt.xticks(runs)
ax4.set_ylabel('Performance (Gflops/s)')
ax4.set_xlabel('Runs')



ax0 = fig.add_subplot(gs[1, 0])
sns.scatterplot(data=node_0_ref, x="complete_time", y="ready_tasks", hue='taskpool_id', palette=colours, ax=ax0).set_title("Node 0", loc='left')
ax0.set_ylabel('#Tasks')
ax0.set_xlabel('Execution time(ns)')
plt.legend([],[], frameon=False)


ax1 = fig.add_subplot(gs[2, 0])
sns.scatterplot(data=node_1_ref, x="complete_time", y="ready_tasks", hue='taskpool_id', palette=colours, ax=ax1).set_title("Node 1", loc='left')
ax1.set_ylabel('#Tasks')
ax1.set_xlabel('Execution time(ns)')
plt.legend([],[], frameon=False)

ax2 = fig.add_subplot(gs[3, 0])
sns.scatterplot(data=node_2_ref, x="complete_time", y="ready_tasks", hue='taskpool_id', palette=colours, ax=ax2).set_title("Node 2", loc='left')
ax2.set_ylabel('#Tasks')
ax2.set_xlabel('Execution time(ns)')
plt.legend([],[], frameon=False)

ax3 = fig.add_subplot(gs[4, 0])
sns.scatterplot(data=node_3_ref, x="complete_time", y="ready_tasks", hue='taskpool_id', palette=colours,  ax=ax3).set_title("Node 3", loc='left')
ax3.set_ylabel('#Tasks')
ax3.set_xlabel('Execution time(ns)')
plt.legend([],[], frameon=False)

fig.savefig('GEMM_tasks_distr.png', dpi=300, bbox_inches='tight')

TypeError: 'module' object is not callable

## Profile READ tasks as well

```
[****] TIME(s)      3.22098 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :    4967.436444 gflops - ENQ&PROG&DEST      3.66241 :    4368.703656 gflops - ENQ      0.28749 - DEST      0.15395
[****] TIME(s)      6.02851 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :    2654.056578 gflops - ENQ&PROG&DEST      6.46031 :    2476.662532 gflops - ENQ      0.28386 - DEST      0.14794
[****] TIME(s)      2.87919 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :    5557.111294 gflops - ENQ&PROG&DEST      4.54857 :    3517.588002 gflops - ENQ      1.51079 - DEST      0.15858
[****] TIME(s)      1.87453 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :    8535.453872 gflops - ENQ&PROG&DEST      3.27446 :    4886.309225 gflops - ENQ      1.25257 - DEST      0.14735
[****] TIME(s)      1.22998 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   13008.321082 gflops - ENQ&PROG&DEST      2.02987 :    7882.291363 gflops - ENQ      0.65180 - DEST      0.14809
[****] TIME(s)      1.14327 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   13994.967303 gflops - ENQ&PROG&DEST      2.56529 :    6237.117040 gflops - ENQ      1.27663 - DEST      0.14539
[****] TIME(s)      1.04338 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   15334.839998 gflops - ENQ&PROG&DEST      1.88256 :    8499.061577 gflops - ENQ      0.70343 - DEST      0.13575
[****] TIME(s)      2.08452 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :    7675.632591 gflops - ENQ&PROG&DEST      2.60477 :    6142.578289 gflops - ENQ      0.38905 - DEST      0.13120
[****] TIME(s)      1.28172 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   12483.235415 gflops - ENQ&PROG&DEST      1.68951 :    9470.223600 gflops - ENQ      0.27398 - DEST      0.13380
[****] TIME(s)      1.61039 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :    9935.503277 gflops - ENQ&PROG&DEST      2.28172 :    7012.245610 gflops - ENQ      0.53835 - DEST      0.13298
[****] TIME(s)      1.01597 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   15748.437204 gflops - ENQ&PROG&DEST      1.71023 :    9355.480052 gflops - ENQ      0.55533 - DEST      0.13892
[****] TIME(s)      1.16663 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   13714.731596 gflops - ENQ&PROG&DEST      1.84482 :    8672.925480 gflops - ENQ      0.54429 - DEST      0.13391
[****] TIME(s)      1.08299 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   14773.869282 gflops - ENQ&PROG&DEST      1.49860 :   10676.664587 gflops - ENQ      0.28109 - DEST      0.13451
[****] TIME(s)      1.06064 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   15085.250659 gflops - ENQ&PROG&DEST      1.46504 :   10921.178887 gflops - ENQ      0.27076 - DEST      0.13365
[****] TIME(s)      1.04738 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   15276.178373 gflops - ENQ&PROG&DEST      2.05948 :    7768.949341 gflops - ENQ      0.87772 - DEST      0.13438
[****] TIME(s)      1.02542 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   15603.312843 gflops - ENQ&PROG&DEST      1.74678 :    9159.687183 gflops - ENQ      0.58988 - DEST      0.13148
[****] TIME(s)      1.04373 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   15329.689608 gflops - ENQ&PROG&DEST      1.46704 :   10906.327045 gflops - ENQ      0.29017 - DEST      0.13314
[****] TIME(s)      1.71460 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :    9331.621583 gflops - ENQ&PROG&DEST      2.12741 :    7520.882818 gflops - ENQ      0.27937 - DEST      0.13344
[****] TIME(s)      1.23063 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   13001.466523 gflops - ENQ&PROG&DEST      1.63325 :    9796.396346 gflops - ENQ      0.26910 - DEST      0.13352
[****] TIME(s)      1.04708 : dgemm     PxQxg=   2 2   4 NB= 1000 N=   20000 :   15280.525065 gflops - ENQ&PROG&DEST      1.49989 :   10667.415171 gflops - ENQ      0.31919 - DEST      0.13362

```

In [ ]:
read_0_hd5 = pd.HDFStore("./traces/GEMM_read-0.prof.h5")
read_0_events = read_0_hd5.events
#node_0_events.tail()

In [ ]:
read_0_events.columns

In [ ]:
read_1_hd5 = pd.HDFStore("./traces/GEMM_read-1.prof.h5")
read_1_events = read_1_hd5.events

In [ ]:
read_2_hd5 = pd.HDFStore("./traces/GEMM_read-2.prof.h5")
read_2_events = read_2_hd5.events

In [ ]:
read_3_hd5 = pd.HDFStore("./traces/GEMM_read-3.prof.h5")
read_3_events = read_3_hd5.events

In [ ]:
read_0_events['tcid'].unique()

In [ ]:
GEMM_task_class_id   = 5
READ_C_task_class_id = 3
READ_B_task_class_id = 2
READ_A_task_class_id = 0

In [ ]:
def filter_data_frame_class(df, class_id):
   
    df = df.astype(float)
    
    # consider only compute kernels
    #df = df.loc[ df['task_type'] == 0 ] 
    
    # remove first run
    df = df.loc[ df['taskpool_id'] > 8 ] 
    df = df.loc[ df['tcid'] == class_id ] 

    
    df.reset_index(drop=True, inplace=True)
    

    
    return df

In [ ]:
tp_id = [10., 12., 14., 16., 22., 24., 26., 28., 30., 32., 34., 36., 38.,
       42., 44., 46., 18., 20., 40.]
tp_id_sort = tp_id.sort()
print(tp_id_sort)

## GEMM Tasks

In [ ]:
df_GEMM_0 = filter_data_frame_class(read_0_events, 0)

In [ ]:


fig = plt.figure(figsize=(20, 20))
gs = GridSpec(nrows=5, ncols=1)

colours=['red','red','orange','orange','orange','orange','orange','blue','blue','red','blue','red','blue', 'blue','red', 'blue', 'orange', 'blue','blue']

gflops = [4567.170588, 4005.209511, 20617.670354, 20134.520392, 19304.971485, 11383.630668, 20456.241068, 17045.157896, 16402.052070, 8891.176050, 12305.456605, 4846.163159, 10353.838489, 16576.485269, 8250.884586, 16008.084627, 19415.471576, 15980.228127, 15464.653143]
runs = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]



ax4 = fig.add_subplot(gs[0, 0])
plt.plot(runs, gflops, marker=11)

plt.axhline(y=8500,  color='red', linestyle='--')
plt.axhline(y=18000,  color='blue', linestyle='--')
plt.axhline(y=24000, color='orange', linestyle='--')

plt.xticks(runs)
ax4.set_ylabel('Performance (Gflops/s)')
ax4.set_xlabel('Runs')



ax0 = fig.add_subplot(gs[1, 0])
sns.scatterplot(data=node_0_ref, x="complete_time", y="ready_tasks", hue='taskpool_id', palette=colours, ax=ax0).set_title("Node 0", loc='left')
ax0.set_ylabel('#Tasks')
ax0.set_xlabel('Execution time(ns)')
plt.legend([],[], frameon=False)


ax1 = fig.add_subplot(gs[2, 0])
sns.scatterplot(data=node_1_ref, x="complete_time", y="ready_tasks", hue='taskpool_id', palette=colours, ax=ax1).set_title("Node 1", loc='left')
ax1.set_ylabel('#Tasks')
ax1.set_xlabel('Execution time(ns)')
plt.legend([],[], frameon=False)

ax2 = fig.add_subplot(gs[3, 0])
sns.scatterplot(data=node_2_ref, x="complete_time", y="ready_tasks", hue='taskpool_id', palette=colours, ax=ax2).set_title("Node 2", loc='left')
ax2.set_ylabel('#Tasks')
ax2.set_xlabel('Execution time(ns)')
plt.legend([],[], frameon=False)

ax3 = fig.add_subplot(gs[4, 0])
sns.scatterplot(data=node_3_ref, x="complete_time", y="ready_tasks", hue='taskpool_id', palette=colours,  ax=ax3).set_title("Node 3", loc='left')
ax3.set_ylabel('#Tasks')
ax3.set_xlabel('Execution time(ns)')
plt.legend([],[], frameon=False)

fig.savefig('GEMM_tasks_distr.png', dpi=300, bbox_inches='tight')

## READ Tasks

In [ ]:

bad_tp = 12

df_read_A_0 = filter_data_frame_class(read_0_events, 0)
df_read_A_0_slow_tp = df_read_A_0.loc[ df_read_A_0['taskpool_id'] == bad_tp]

df_read_B_0 = filter_data_frame_class(read_0_events, 2)
df_read_B_0_slow_tp = df_read_B_0.loc[ df_read_B_0['taskpool_id'] == bad_tp]

df_read_C_0 = filter_data_frame_class(read_0_events, 3)
df_read_C_0_slow_tp = df_read_C_0.loc[ df_read_C_0['taskpool_id'] == bad_tp]

df_read_A_1 = filter_data_frame_class(read_1_events, 0)
df_read_A_1_slow_tp = df_read_A_1.loc[ df_read_A_1['taskpool_id'] == bad_tp]

df_read_B_1 = filter_data_frame_class(read_1_events, 2)
df_read_B_1_slow_tp = df_read_B_1.loc[ df_read_B_1['taskpool_id'] == bad_tp]

df_read_C_1 = filter_data_frame_class(read_1_events, 3)
df_read_C_1_slow_tp = df_read_C_1.loc[ df_read_C_1['taskpool_id'] == bad_tp]

df_read_A_2 = filter_data_frame_class(read_2_events, 0)
df_read_A_2_slow_tp = df_read_A_2.loc[ df_read_A_2['taskpool_id'] == bad_tp]

df_read_B_2 = filter_data_frame_class(read_2_events, 2)
df_read_B_2_slow_tp = df_read_B_2.loc[ df_read_B_2['taskpool_id'] == bad_tp]

df_read_C_2 = filter_data_frame_class(read_2_events, 3)
df_read_C_2_slow_tp = df_read_C_2.loc[ df_read_C_2['taskpool_id'] == bad_tp]

df_read_A_3 = filter_data_frame_class(read_3_events, 0)
df_read_A_3_slow_tp = df_read_A_3.loc[ df_read_A_3['taskpool_id'] == bad_tp]

df_read_B_3 = filter_data_frame_class(read_3_events, 2)
df_read_B_3_slow_tp = df_read_B_3.loc[ df_read_B_3['taskpool_id'] == bad_tp]

df_read_C_3 = filter_data_frame_class(read_3_events, 3)
df_read_C_3_slow_tp = df_read_C_3.loc[ df_read_C_3['taskpool_id'] == bad_tp]

In [ ]:
fig = plt.figure(figsize=(10, 20))
gs = GridSpec(nrows=4, ncols=1)

#colours=['red','red','orange','orange','orange','orange','orange','blue','blue','red','blue','red','blue', 'blue','red', 'blue', 'orange', 'blue','blue']


ax0 = fig.add_subplot(gs[0, 0])
sns.scatterplot(data=df_read_A_0_slow_tp, x="begin", y=1, label='READ_A', ax=ax0).set_title("Node 0", loc='left')

sns.scatterplot(data=df_read_B_0_slow_tp, x="begin", y=2, label='READ_B', ax=ax0).set_title("Node 0", loc='left')

sns.scatterplot(data=df_read_C_0_slow_tp, x="begin", y=3, label='READ_C', ax=ax0).set_title("Node 0", loc='left')

ax0.set_ylabel(' ')
ax0.set_xlabel('Execution time(ns)')



ax1 = fig.add_subplot(gs[1, 0])
sns.scatterplot(data=df_read_A_1_slow_tp, x="begin", y=1, label='READ_A', ax=ax1).set_title("Node 1", loc='left')

sns.scatterplot(data=df_read_B_1_slow_tp, x="begin", y=2, label='READ_B', ax=ax1).set_title("Node 1", loc='left')

sns.scatterplot(data=df_read_C_1_slow_tp, x="begin", y=3, label='READ_C', ax=ax1).set_title("Node 1", loc='left')

ax1.set_ylabel(' ')
ax1.set_xlabel('Execution time(ns)')


ax2 = fig.add_subplot(gs[2, 0])
sns.scatterplot(data=df_read_A_2_slow_tp, x="begin", y=1, label='READ_A', ax=ax2).set_title("Node 2", loc='left')

sns.scatterplot(data=df_read_B_2_slow_tp, x="begin", y=2, label='READ_B', ax=ax2).set_title("Node 2", loc='left')

sns.scatterplot(data=df_read_C_2_slow_tp, x="begin", y=3, label='READ_C', ax=ax2).set_title("Node 2", loc='left')

ax2.set_ylabel(' ')
ax2.set_xlabel('Execution time(ns)')



ax3 = fig.add_subplot(gs[3, 0])
sns.scatterplot(data=df_read_A_3_slow_tp, x="begin", y=1, label='READ_A', ax=ax3).set_title("Node 3", loc='left')

sns.scatterplot(data=df_read_B_3_slow_tp, x="begin", y=2, label='READ_B', ax=ax3).set_title("Node 3", loc='left')

sns.scatterplot(data=df_read_C_3_slow_tp, x="begin", y=3, label='READ_C', ax=ax3).set_title("Node 3", loc='left')

ax3.set_ylabel(' ')
ax3.set_xlabel('Execution time(ns)')

## GOOD performance

In [ ]:
good_tp = 44

df_read_A_0 = filter_data_frame_class(read_0_events, 0)
df_read_A_0_fast_tp = df_read_A_0.loc[ df_read_A_0['taskpool_id'] == good_tp]

df_read_B_0 = filter_data_frame_class(read_0_events, 2)
df_read_B_0_fast_tp = df_read_B_0.loc[ df_read_B_0['taskpool_id'] == good_tp]

df_read_C_0 = filter_data_frame_class(read_0_events, 3)
df_read_C_0_fast_tp = df_read_C_0.loc[ df_read_C_0['taskpool_id'] == good_tp]

df_read_A_1 = filter_data_frame_class(read_1_events, 0)
df_read_A_1_fast_tp = df_read_A_1.loc[ df_read_A_1['taskpool_id'] == good_tp]

df_read_B_1 = filter_data_frame_class(read_1_events, 2)
df_read_B_1_fast_tp = df_read_B_1.loc[ df_read_B_1['taskpool_id'] == good_tp]

df_read_C_1 = filter_data_frame_class(read_1_events, 3)
df_read_C_1_fast_tp = df_read_C_1.loc[ df_read_C_1['taskpool_id'] == good_tp]

df_read_A_2 = filter_data_frame_class(read_2_events, 0)
df_read_A_2_fast_tp = df_read_A_2.loc[ df_read_A_2['taskpool_id'] == good_tp]

df_read_B_2 = filter_data_frame_class(read_2_events, 2)
df_read_B_2_fast_tp = df_read_B_2.loc[ df_read_B_2['taskpool_id'] == good_tp]

df_read_C_2 = filter_data_frame_class(read_2_events, 3)
df_read_C_2_fast_tp = df_read_C_2.loc[ df_read_C_2['taskpool_id'] == good_tp]

df_read_A_3 = filter_data_frame_class(read_3_events, 0)
df_read_A_3_fast_tp = df_read_A_3.loc[ df_read_A_3['taskpool_id'] == good_tp]

df_read_B_3 = filter_data_frame_class(read_3_events, 2)
df_read_B_3_fast_tp = df_read_B_3.loc[ df_read_B_3['taskpool_id'] == good_tp]

df_read_C_3 = filter_data_frame_class(read_3_events, 3)
df_read_C_3_fast_tp = df_read_C_3.loc[ df_read_C_3['taskpool_id'] == good_tp]

In [ ]:
fig = plt.figure(figsize=(10, 20))
gs = GridSpec(nrows=4, ncols=1)

#colours=['red','red','orange','orange','orange','orange','orange','blue','blue','red','blue','red','blue', 'blue','red', 'blue', 'orange', 'blue','blue']


ax0 = fig.add_subplot(gs[0, 0])
sns.scatterplot(data=df_read_A_0_fast_tp, x="begin", y=1, label='READ_A', ax=ax0).set_title("Node 0", loc='left')

sns.scatterplot(data=df_read_B_0_fast_tp, x="begin", y=2, label='READ_B', ax=ax0).set_title("Node 0", loc='left')

sns.scatterplot(data=df_read_C_0_fast_tp, x="begin", y=3, label='READ_C', ax=ax0).set_title("Node 0", loc='left')

ax0.set_ylabel(' ')
ax0.set_xlabel('Execution time(ns)')



ax1 = fig.add_subplot(gs[1, 0])
sns.scatterplot(data=df_read_A_1_fast_tp, x="begin", y=1, label='READ_A', ax=ax1).set_title("Node 1", loc='left')

sns.scatterplot(data=df_read_B_1_fast_tp, x="begin", y=2, label='READ_B', ax=ax1).set_title("Node 1", loc='left')

sns.scatterplot(data=df_read_C_1_fast_tp, x="begin", y=3, label='READ_C', ax=ax1).set_title("Node 1", loc='left')

ax1.set_ylabel(' ')
ax1.set_xlabel('Execution time(ns)')


ax2 = fig.add_subplot(gs[2, 0])
sns.scatterplot(data=df_read_A_2_fast_tp, x="begin", y=1, label='READ_A', ax=ax2).set_title("Node 2", loc='left')

sns.scatterplot(data=df_read_B_2_fast_tp, x="begin", y=2, label='READ_B', ax=ax2).set_title("Node 2", loc='left')

sns.scatterplot(data=df_read_C_2_fast_tp, x="begin", y=3, label='READ_C', ax=ax2).set_title("Node 2", loc='left')

ax2.set_ylabel(' ')
ax2.set_xlabel('Execution time(ns)')



ax3 = fig.add_subplot(gs[3, 0])
sns.scatterplot(data=df_read_A_3_fast_tp, x="begin", y=1, label='READ_A', ax=ax3).set_title("Node 3", loc='left')

sns.scatterplot(data=df_read_B_3_fast_tp, x="begin", y=2, label='READ_B', ax=ax3).set_title("Node 3", loc='left')

sns.scatterplot(data=df_read_C_3_fast_tp, x="begin", y=3, label='READ_C', ax=ax3).set_title("Node 3", loc='left')

ax3.set_ylabel(' ')
ax3.set_xlabel('Execution time(ns)')

## Combined

In [ ]:
fig = plt.figure(figsize=(30, 20))
gs = GridSpec(nrows=4, ncols=2)

ax0 = fig.add_subplot(gs[0, 0])
sns.scatterplot(data=df_read_A_0_slow_tp, x="begin", y=1, label='READ_A', ax=ax0).set_title("Node 0", loc='left')

sns.scatterplot(data=df_read_B_0_slow_tp, x="begin", y=2, label='READ_B', ax=ax0).set_title("Node 0", loc='left')

sns.scatterplot(data=df_read_C_0_slow_tp, x="begin", y=3, label='READ_C', ax=ax0).set_title("Node 0", loc='left')

ax0.set_ylabel(' ')
ax0.set_yticklabels([])
ax0.set_xlabel('Execution time(ns)')
ax0.set_title('Slow Run')



ax1 = fig.add_subplot(gs[1, 0])
sns.scatterplot(data=df_read_A_1_slow_tp, x="begin", y=1, label='READ_A', ax=ax1).set_title("Node 1", loc='left')

sns.scatterplot(data=df_read_B_1_slow_tp, x="begin", y=2, label='READ_B', ax=ax1).set_title("Node 1", loc='left')

sns.scatterplot(data=df_read_C_1_slow_tp, x="begin", y=3, label='READ_C', ax=ax1).set_title("Node 1", loc='left')

ax1.set_ylabel(' ')
ax1.set_yticklabels([])
ax1.set_xlabel('Execution time(ns)')


ax2 = fig.add_subplot(gs[2, 0])
sns.scatterplot(data=df_read_A_2_slow_tp, x="begin", y=1, label='READ_A', ax=ax2).set_title("Node 2", loc='left')

sns.scatterplot(data=df_read_B_2_slow_tp, x="begin", y=2, label='READ_B', ax=ax2).set_title("Node 2", loc='left')

sns.scatterplot(data=df_read_C_2_slow_tp, x="begin", y=3, label='READ_C', ax=ax2).set_title("Node 2", loc='left')

ax2.set_ylabel(' ')
ax2.set_yticklabels([])
ax2.set_xlabel('Execution time(ns)')



ax3 = fig.add_subplot(gs[3, 0])
sns.scatterplot(data=df_read_A_3_slow_tp, x="begin", y=1, label='READ_A', ax=ax3).set_title("Node 3", loc='left')

sns.scatterplot(data=df_read_B_3_slow_tp, x="begin", y=2, label='READ_B', ax=ax3).set_title("Node 3", loc='left')

sns.scatterplot(data=df_read_C_3_slow_tp, x="begin", y=3, label='READ_C', ax=ax3).set_title("Node 3", loc='left')

ax3.set_ylabel(' ')
ax3.set_yticklabels([])
ax3.set_xlabel('Execution time(ns)')


########

ax4 = fig.add_subplot(gs[0,1])
sns.scatterplot(data=df_read_A_0_fast_tp, x="begin", y=1, label='READ_A', ax=ax4).set_title("Node 0", loc='left')

sns.scatterplot(data=df_read_B_0_fast_tp, x="begin", y=2, label='READ_B', ax=ax4).set_title("Node 0", loc='left')

sns.scatterplot(data=df_read_C_0_fast_tp, x="begin", y=3, label='READ_C', ax=ax4).set_title("Node 0", loc='left')

ax4.set_ylabel(' ')
ax4.set_yticklabels([])
ax4.set_xlabel('Execution time(ns)')
ax4.set_title('Fast Run')



ax5 = fig.add_subplot(gs[1, 1])
sns.scatterplot(data=df_read_A_1_fast_tp, x="begin", y=1, label='READ_A', ax=ax5).set_title("Node 1", loc='left')

sns.scatterplot(data=df_read_B_1_fast_tp, x="begin", y=2, label='READ_B', ax=ax5).set_title("Node 1", loc='left')

sns.scatterplot(data=df_read_C_1_fast_tp, x="begin", y=3, label='READ_C', ax=ax5).set_title("Node 1", loc='left')

ax5.set_ylabel(' ')
ax5.set_yticklabels([])
ax5.set_xlabel('Execution time(ns)')


ax6 = fig.add_subplot(gs[2, 1])
sns.scatterplot(data=df_read_A_2_fast_tp, x="begin", y=1, label='READ_A', ax=ax6).set_title("Node 2", loc='left')

sns.scatterplot(data=df_read_B_2_fast_tp, x="begin", y=2, label='READ_B', ax=ax6).set_title("Node 2", loc='left')

sns.scatterplot(data=df_read_C_2_fast_tp, x="begin", y=3, label='READ_C', ax=ax6).set_title("Node 2", loc='left')

ax6.set_ylabel(' ')
ax6.set_yticklabels([])
ax6.set_xlabel('Execution time(ns)')

ax7 = fig.add_subplot(gs[3, 1])
sns.scatterplot(data=df_read_A_3_fast_tp, x="begin", y=1, label='READ_A', ax=ax7).set_title("Node 3", loc='left')

sns.scatterplot(data=df_read_B_3_fast_tp, x="begin", y=2, label='READ_B', ax=ax7).set_title("Node 3", loc='left')

sns.scatterplot(data=df_read_C_3_fast_tp, x="begin", y=3, label='READ_C', ax=ax7).set_title("Node 3", loc='left')

ax7.set_ylabel(' ')
ax7.set_yticklabels([])
ax7.set_xlabel('Execution time(ns)')

plt.savefig('READ_tasks_combined.jpeg')